apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-java-app
spec:
  inputs:
    params:
      - name: contextDir
        description: The context directory within sources
        default: .
        type: string
    resources:
      - name: buildSource
        type: git
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: maven-build
      image: docker.io/maven:3.6.3-jdk-8-slim
      workingDir: "/workspace/buildSource/$(params.contextDir)"
      command:
        - mvn
      args:
        - -DskipTests
        - clean install
    - name: list-directory
      image: busybox
      workingDir: "/workspace/buildSource/$(params.contextDir)"
      command:
        - ls
      args:
        - -ltr
