---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/redhat-deveoper-demos/dnmc-tekton-demos
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: greeter-imae
spec:
  type: image
  params:
    - name: url
      value: docker.io/rhdevelopers/dnmc-tekton-greeter
