apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helloworld
spec:
  inputs: {}
  outputs: {}
  steps:
    - name: say-hello
      image: busybox
      command: ["echo"]
      args:
        - "hello world"
